    name: Process Activity Log

    on:
      push:
        paths:
          - 'Activity_log.txt'

    jobs:
      parse:
        runs-on: ubuntu-latest
        steps:
          - uses: actions/checkout@v3
          - name: Display log
            run: |
              echo "::group::Activity Log"
              cat Activity_log.txt
              echo "::endgroup::"
    